//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach.Views.Windows.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kursach.Views.Windows.Resources.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string m_AboutApp {
            get {
                return ResourceManager.GetString("m_AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учётная запись.
        /// </summary>
        public static string m_Account {
            get {
                return ResourceManager.GetString("m_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string m_Add {
            get {
                return ResourceManager.GetString("m_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить товар.
        /// </summary>
        public static string m_Add_Product {
            get {
                return ResourceManager.GetString("m_Add_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уже существует.
        /// </summary>
        public static string m_Already_exists {
            get {
                return ResourceManager.GetString("m_Already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string m_Authorization {
            get {
                return ResourceManager.GetString("m_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По категории:.
        /// </summary>
        public static string m_By_Category {
            get {
                return ResourceManager.GetString("m_By_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дате.
        /// </summary>
        public static string m_By_Date {
            get {
                return ResourceManager.GetString("m_By_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По названию.
        /// </summary>
        public static string m_By_Name {
            get {
                return ResourceManager.GetString("m_By_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По названию:.
        /// </summary>
        public static string m_By_Name1 {
            get {
                return ResourceManager.GetString("m_By_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По количеству:.
        /// </summary>
        public static string m_By_Number {
            get {
                return ResourceManager.GetString("m_By_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По цене.
        /// </summary>
        public static string m_By_Price {
            get {
                return ResourceManager.GetString("m_By_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От:.
        /// </summary>
        public static string m_By_Price_From {
            get {
                return ResourceManager.GetString("m_By_Price_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До:.
        /// </summary>
        public static string m_By_Price_To {
            get {
                return ResourceManager.GetString("m_By_Price_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По рейтингу.
        /// </summary>
        public static string m_By_Rating {
            get {
                return ResourceManager.GetString("m_By_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По размеру:.
        /// </summary>
        public static string m_By_Size {
            get {
                return ResourceManager.GetString("m_By_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По пользователю:.
        /// </summary>
        public static string m_By_User {
            get {
                return ResourceManager.GetString("m_By_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string m_Category {
            get {
                return ResourceManager.GetString("m_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует категория.
        /// </summary>
        public static string m_Category_missing {
            get {
                return ResourceManager.GetString("m_Category_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить/Удалить продукт.
        /// </summary>
        public static string m_Change_Del_Product {
            get {
                return ResourceManager.GetString("m_Change_Del_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить учётную запись.
        /// </summary>
        public static string m_ChangeAccount {
            get {
                return ResourceManager.GetString("m_ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить поля.
        /// </summary>
        public static string m_Clear {
            get {
                return ResourceManager.GetString("m_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string m_ComeIn {
            get {
                return ResourceManager.GetString("m_ComeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тёмная.
        /// </summary>
        public static string m_DarkTheme {
            get {
                return ResourceManager.GetString("m_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата продажи.
        /// </summary>
        public static string m_Date_Of_Sale {
            get {
                return ResourceManager.GetString("m_Date_Of_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранное.
        /// </summary>
        public static string m_Delete_Object {
            get {
                return ResourceManager.GetString("m_Delete_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string m_Description {
            get {
                return ResourceManager.GetString("m_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        public static string m_Enter_Log {
            get {
                return ResourceManager.GetString("m_Enter_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string m_Enter_Pas {
            get {
                return ResourceManager.GetString("m_Enter_Pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string m_Exit {
            get {
                return ResourceManager.GetString("m_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя продукта, который хотите изменить:.
        /// </summary>
        public static string m_Help_With_Change {
            get {
                return ResourceManager.GetString("m_Help_With_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на и его новые свойства:.
        /// </summary>
        public static string m_Help_With_Change_Fields {
            get {
                return ResourceManager.GetString("m_Help_With_Change_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя продукта, который хотите удалить:.
        /// </summary>
        public static string m_Help_With_Delete {
            get {
                return ResourceManager.GetString("m_Help_With_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат даты. Правильный формат: 2021-05-20.
        /// </summary>
        public static string m_Invalid_date_format {
            get {
                return ResourceManager.GetString("m_Invalid_date_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно введённая дата продажи.
        /// </summary>
        public static string m_Invalid_date_of_sale {
            get {
                return ResourceManager.GetString("m_Invalid_date_of_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат цены. Правильный формат: 12356,67.
        /// </summary>
        public static string m_Invalid_price_format {
            get {
                return ResourceManager.GetString("m_Invalid_price_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат количества. Правильный формат: 777.
        /// </summary>
        public static string m_Invalid_quantity_format {
            get {
                return ResourceManager.GetString("m_Invalid_quantity_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат рейтинга. Правильный формат: 6,7.
        /// </summary>
        public static string m_Invalid_rating_format {
            get {
                return ResourceManager.GetString("m_Invalid_rating_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат размера. Правильный формат: 200х300.
        /// </summary>
        public static string m_Invalid_size_format {
            get {
                return ResourceManager.GetString("m_Invalid_size_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат времени. Правильный формат: 15:40.
        /// </summary>
        public static string m_Invalid_time_format {
            get {
                return ResourceManager.GetString("m_Invalid_time_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно введённое время продажи.
        /// </summary>
        public static string m_Invalid_time_of_sale {
            get {
                return ResourceManager.GetString("m_Invalid_time_of_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утюг.
        /// </summary>
        public static string m_Iron {
            get {
                return ResourceManager.GetString("m_Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string m_Lang {
            get {
                return ResourceManager.GetString("m_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        public static string m_Lang_en {
            get {
                return ResourceManager.GetString("m_Lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string m_Lang_ru {
            get {
                return ResourceManager.GetString("m_Lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая.
        /// </summary>
        public static string m_LightTheme {
            get {
                return ResourceManager.GetString("m_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить картинку.
        /// </summary>
        public static string m_Load_Picture {
            get {
                return ResourceManager.GetString("m_Load_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует логин.
        /// </summary>
        public static string m_Login_missing {
            get {
                return ResourceManager.GetString("m_Login_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основная.
        /// </summary>
        public static string m_MainTheme {
            get {
                return ResourceManager.GetString("m_MainTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string m_Message {
            get {
                return ResourceManager.GetString("m_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует количество.
        /// </summary>
        public static string m_Missing_number {
            get {
                return ResourceManager.GetString("m_Missing_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует цена.
        /// </summary>
        public static string m_Missing_price {
            get {
                return ResourceManager.GetString("m_Missing_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует название продукта.
        /// </summary>
        public static string m_Missing_product_name {
            get {
                return ResourceManager.GetString("m_Missing_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует рейтинг.
        /// </summary>
        public static string m_Missing_rating {
            get {
                return ResourceManager.GetString("m_Missing_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует размер.
        /// </summary>
        public static string m_Missing_size {
            get {
                return ResourceManager.GetString("m_Missing_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название товара.
        /// </summary>
        public static string m_NOP {
            get {
                return ResourceManager.GetString("m_NOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноутбук.
        /// </summary>
        public static string m_Notebook {
            get {
                return ResourceManager.GetString("m_Notebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string m_Number {
            get {
                return ResourceManager.GetString("m_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести.
        /// </summary>
        public static string m_Output {
            get {
                return ResourceManager.GetString("m_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно введен пароль.
        /// </summary>
        public static string m_Password_entered_incorrectly {
            get {
                return ResourceManager.GetString("m_Password_entered_incorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают.
        /// </summary>
        public static string m_Password_mismatch {
            get {
                return ResourceManager.GetString("m_Password_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует пароль.
        /// </summary>
        public static string m_Password_missing {
            get {
                return ResourceManager.GetString("m_Password_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string m_Phone {
            get {
                return ResourceManager.GetString("m_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена 1 шт..
        /// </summary>
        public static string m_Price {
            get {
                return ResourceManager.GetString("m_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар добавлен.
        /// </summary>
        public static string m_Product_added {
            get {
                return ResourceManager.GetString("m_Product_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар изменён.
        /// </summary>
        public static string m_Product_changed {
            get {
                return ResourceManager.GetString("m_Product_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список товаров пуст.
        /// </summary>
        public static string m_Product_list_is_empty {
            get {
                return ResourceManager.GetString("m_Product_list_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар удалён.
        /// </summary>
        public static string m_Product_removed {
            get {
                return ResourceManager.GetString("m_Product_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг.
        /// </summary>
        public static string m_Rating {
            get {
                return ResourceManager.GetString("m_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string m_Registration {
            get {
                return ResourceManager.GetString("m_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        public static string m_Repeat_Pas {
            get {
                return ResourceManager.GetString("m_Repeat_Pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для смены языка, перезапустите приложение!.
        /// </summary>
        public static string m_RestartApp {
            get {
                return ResourceManager.GetString("m_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует дата продажи.
        /// </summary>
        public static string m_Sale_date_missing {
            get {
                return ResourceManager.GetString("m_Sale_date_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует время продажи.
        /// </summary>
        public static string m_Sale_time_is_missing {
            get {
                return ResourceManager.GetString("m_Sale_time_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить изменения.
        /// </summary>
        public static string m_Save_Changes {
            get {
                return ResourceManager.GetString("m_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить картинку.
        /// </summary>
        public static string m_Save_Picture {
            get {
                return ResourceManager.GetString("m_Save_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string m_Search {
            get {
                return ResourceManager.GetString("m_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск проданных продуктов.
        /// </summary>
        public static string m_Search_Sold {
            get {
                return ResourceManager.GetString("m_Search_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти.
        /// </summary>
        public static string m_Searching {
            get {
                return ResourceManager.GetString("m_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string m_Sign_Up {
            get {
                return ResourceManager.GetString("m_Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер.
        /// </summary>
        public static string m_Size {
            get {
                return ResourceManager.GetString("m_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проданные продукты.
        /// </summary>
        public static string m_Sold_Products {
            get {
                return ResourceManager.GetString("m_Sold_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string m_Sort {
            get {
                return ResourceManager.GetString("m_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсортировать.
        /// </summary>
        public static string m_Sorting {
            get {
                return ResourceManager.GetString("m_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно открыть выбранный файл.
        /// </summary>
        public static string m_The_selected_file_cannot_be_opened {
            get {
                return ResourceManager.GetString("m_The_selected_file_cannot_be_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранного товара не существует.
        /// </summary>
        public static string m_The_selected_product_does_not_exist {
            get {
                return ResourceManager.GetString("m_The_selected_product_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранное количество товара превышает допустимое.
        /// </summary>
        public static string m_The_selected_quantity_of_products_exceeds_the_allowable {
            get {
                return ResourceManager.GetString("m_The_selected_quantity_of_products_exceeds_the_allowable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранного пользователя не существует.
        /// </summary>
        public static string m_The_selected_user_does_not_exist {
            get {
                return ResourceManager.GetString("m_The_selected_user_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темы.
        /// </summary>
        public static string m_Themes {
            get {
                return ResourceManager.GetString("m_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого товара не существует.
        /// </summary>
        public static string m_This_product_does_not_exist {
            get {
                return ResourceManager.GetString("m_This_product_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого пользователя не существует.
        /// </summary>
        public static string m_This_user_does_not_exist {
            get {
                return ResourceManager.GetString("m_This_user_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время продажи.
        /// </summary>
        public static string m_Time_Of_Sale {
            get {
                return ResourceManager.GetString("m_Time_Of_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь добавлен.
        /// </summary>
        public static string m_User_added {
            get {
                return ResourceManager.GetString("m_User_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует логин пользователя.
        /// </summary>
        public static string m_User_login_missing {
            get {
                return ResourceManager.GetString("m_User_login_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин пользователя.
        /// </summary>
        public static string m_Users_Login {
            get {
                return ResourceManager.GetString("m_Users_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невверно введены значения!.
        /// </summary>
        public static string m_Values_entered_incorrectly {
            get {
                return ResourceManager.GetString("m_Values_entered_incorrectly", resourceCulture);
            }
        }
    }
}
